- name: Load DR Resources
  hosts: localhost
  vars:
    cred_template: {{aws_ssh_key}}
              template: "'{{aws_ssh_key}}'"
        extra_vars:
          aws_key_file: \'{{tower.filename}}\'
          aws_username: \'{{awsusername}}\'
  roles:
    - authenticate_controller

  tasks:
    - name: Import all assets from our export
      awx.awx.import:
        assets: "{{ export_content.assets }}"