- name: Load DR Resources
  hosts: localhost

  roles:
    - authenticate_controller

  tasks:
    - name: Import all assets from our export
      awx.awx.import:
        assets: "{{ export_content.assets }}"