- name: Load DR Resources
  hosts: localhost
  
  roles:
    - authenticate_controller

  tasks:
    - name: Import all assets from our export
      ansible.controller.import:
        assets: "{{ export_content.assets }}"
        controller_host: "{{ controller_hostname }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: false
...