- name: see if smart inventories included with export task
  hosts: localhost

  

  tasks:
    - name: Authenticate into Automation Controller
      include-role: authenticate_controller
      
    - name: Export all inventories
      ansible.controller.export:
        inventory: 'all'
      register: export_content

    - debug:
        var: "{{ export_content | to_nice_yaml }}"
