- name: see if smart inventories included with export task
  hosts: localhost

  tasks:
    - name: Authenticate into Automation Controller
      include_role: 
        name: authenticate_controller

    - name: Export all inventories
      ansible.controller.export:
        all: True
        controller_host: "{{ controller_hostname }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: false
      register: export_content

    - debug:
        var: export_content
