- name: see if smart inventories included with export task
  hosts: localhost

  tasks:
#    - name: Authenticate into Automation Controller
#      include_role: 
#        name: authenticate_controller

    - name: Export all Assets
      ansible.controller.export:
        all: True
      register: export_content

    - debug:
        var: export_content
